name: Node.js CI

env:
  node-version: 18.x

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Lint
      run: pnpm -r lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Test
      run: pnpm -r test:dump
  perf-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Performance tests
      run: pnpm -r test:perf
