name: Node.js CI

env:
  node-version: 18.x
  NODE_OPTIONS: --max_old_space_size=8192

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Lint
      run: pnpm -r lint
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Generate site
      run: node scripts/site.mjs
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: _site
        destination: .ghpages
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Test
      run: pnpm -r test:dump
  perf-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Performance tests
      run: pnpm -r test:perf
